version: '3'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - my_dbdata:/var/lib/postgresql/data
  api:
    build: .
    ports:
      - "8000:8000"
volumes:
  my_dbdata:
